server:
  port: 8080

app:
  datasource:
    write:
      url: jdbc:mysql://${DB_WRITE_HOST:localhost}:${DB_WRITE_PORT:3306}/${DB_NAME:seckill_demo}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:root}
      driver-class-name: com.mysql.cj.jdbc.Driver
    read:
      url: jdbc:mysql://${DB_READ_HOST:localhost}:${DB_READ_PORT:3306}/${DB_NAME:seckill_demo}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:root}
      driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  elasticsearch:
    uris: http://${ES_HOST:localhost}:${ES_PORT:9200}
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    hikari:
      maximum-pool-size: 10
  jackson:
    serialization:
      indent_output: true

logging:
  level:
    org.springframework.data.elasticsearch.client.WIRE: error
